// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateDirectory(arg1) {
  return window['go']['main']['App']['CreateDirectory'](arg1);
}

export function Exit() {
  return window['go']['main']['App']['Exit']();
}

export function GetCurrentDirectory() {
  return window['go']['main']['App']['GetCurrentDirectory']();
}

export function GetDirectoryContent(arg1) {
  return window['go']['main']['App']['GetDirectoryContent'](arg1);
}

export function GetDirectoryFiles(arg1) {
  return window['go']['main']['App']['GetDirectoryFiles'](arg1);
}

export function GetSubdirectoriesRecursively(arg1) {
  return window['go']['main']['App']['GetSubdirectoriesRecursively'](arg1);
}

export function Move(arg1, arg2) {
  return window['go']['main']['App']['Move'](arg1, arg2);
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function Remove(arg1) {
  return window['go']['main']['App']['Remove'](arg1);
}

export function Rename(arg1) {
  return window['go']['main']['App']['Rename'](arg1);
}

export function SelectDirectory(arg1, arg2) {
  return window['go']['main']['App']['SelectDirectory'](arg1, arg2);
}
