// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateDirectory(arg1:string):Promise<main.FileInfo>;

export function Exit():Promise<void>;

export function GetCurrentDirectory():Promise<string>;

export function GetDirectoryContent(arg1:string):Promise<Array<main.FileInfo>>;

export function GetDirectoryFiles(arg1:string):Promise<Array<main.FileInfo>>;

export function GetSubdirectoriesRecursively(arg1:string):Promise<Array<main.FileInfo>>;

export function Move(arg1:Array<string>,arg2:string):Promise<Array<main.FileInfo>>;

export function OpenFile(arg1:string):Promise<Error>;

export function Remove(arg1:string):Promise<main.FileInfo>;

export function Rename(arg1:Array<main.Renaming>):Promise<Array<main.FileInfo>>;

export function SelectDirectory(arg1:string,arg2:string):Promise<string>;
